variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: api-valor-combustivel 

stages:
  - build
  - deploy

build:
  image: docker:24.0.9
  services:
    - name: docker:24.0.9-dind
  stage: build
  only:
    - main
  script:
    
    - echo "nameserver 192.168.1.8" | tee /etc/resolv.conf
    - docker login "$REGISTRY_ADDRESS" --username "$REGISTRY_USERNAME" --password "$REGISTRY_PASSWORD"    
    - docker build -t "$REGISTRY_ADDRESS/$IMAGE_NAME:latest" .
    - docker push "$REGISTRY_ADDRESS/$IMAGE_NAME:latest"

deploy:
  stage: deploy
  only: 
    - main
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment "Default" --stack "API-Valor-combustivel" --service "API-Valor-combustivel" --new-image "$REGISTRY_ADDRESS/$IMAGE_NAME:latest"