version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres-local
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: combustivel
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: api-combustivel
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://admin:admin@db:5432/combustivel"
